game/config/routes.rb
Rails.application.routes.draw do
  get 'admin/index'

  devise_for :users
  resources :dashboard, :pictures, :admin, :play

  get '/admin/serve/:id', to: 'admin#serve'

  root 'home#index'

end

game/app/models/pictures.rb
class Pictures < ActiveRecord::Base
end

game/app/models/score.rb
class Score < ActiveRecord::Base
end

game/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

game/app/controllers/admin_controller.rb
class AdminController < ApplicationController
  	def index
  		if current_user.email == "admin@xyz.com"
  			@users = User.all
	  		@pics = Pictures.all
	  	else
	  		redirect_to '/'
	  	end
  	end

  	def serve
		@photo = Pictures.find(params[:id])
		send_data(@photo.data, :type => @photo.mime_type, :filename => "#{@photo.filename}.jpg", :disposition => "inline")
	end

end

game/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

game/app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
	before_filter :authenticate_user!
	def index
		if current_user.email == 'admin@xyz.com'
			redirect_to :controller=>'admin', :action => 'index'
		end
	end	
end

game/app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
		if user_signed_in?
    		redirect_to :controller=>'dashboard', :action => 'index'
  		end		
	end

end

game/app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
	def new
		@pic = Pictures.new
  	end

	def create
		@pic = Pictures.new(params_data) do |t|
      		if params[:pictures][:data]
       		 	t.data      = params[:pictures][:data].read
        		t.filename  = params[:pictures][:data].original_filename
		        t.mime_type = params[:pictures][:data].content_type
      		end
    	end
    
    # normal save
	    if @pic.save
   		   	redirect_to(dashboard_index_path)
    	else
     		render :action => "new"
    	end		
   	end

   	def destroy
		@pic = Pictures.find(params[:id])
		@pic.destroy
		redirect_to(root_path)
	end
   	private
	def params_data
    	params.require(:pictures).permit(:tag)
  	end
end

game/app/controllers/play_controller.rb
class PlayController < ApplicationController
	def index
		@pics = Pictures.all
		@last_id = Pictures.last.id
		@rand = 1
		while 1 do
			@rand = Random.rand(@last_id) + 1
			if not (@rand == 2)
				break
			end
		end
		@attempts = 3
		@tag = Pictures.find(@rand)
		@selected = Pictures.where(tag: @tag.tag)
	end

	def saveScore
		@score = Scores.new
		@stored_score = cookie[:score]
	end
end

game/app/helpers/admin_helper.rb
module AdminHelper
end

game/app/helpers/application_helper.rb
module ApplicationHelper
end

game/app/helpers/dashboard_helper.rb
module DashboardHelper
end

game/app/helpers/home_helper.rb
module HomeHelper
end

game/app/helpers/pictures_helper.rb
module PicturesHelper
end

game/app/helpers/play_helper.rb
module PlayHelper
end

game/app/views/admin/index.html.erb
<center><h1>Admin Panel</h1></center>

<h2>Users</h2>

<div style="padding: 5px 10px 0px 10px;margin-left: 5%; margin-top: 3%;margin-right: 5%;background: white;box-shadow:0px 10px 20px 3px #d3d3d3;padding-bottom:50px;">
<table>
  <thead>
    <tr>
      <th style="padding-right:5em">S.no</th>
      <th>Email</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
      	<td style="padding-right:5em"><%= user.id %> </td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', edit_user_registration_path(user) %></td>
        <td><%= link_to 'Edit/Delete', edit_user_registration_path(user) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
</div>
<br>
<h2>Pictures</h2>

<div style="padding: 5px 10px 0px 10px;margin-left: 5%; margin-top: 3%;margin-right: 5%;background: white;box-shadow:0px 10px 20px 3px #d3d3d3;padding-bottom:50px;">
<span style="right:0;"><%= link_to "Add Pictures" , new_picture_path %></span>
<table>
  <thead>
    <tr>
      <th style="padding-right:5em">S.no</th>
      <th style="padding-right:5em">Tag</th>
      <th>Pic</th>
    </tr>
  </thead>

  <tbody>
    <% @pics.each do |pic| %>
      <tr>
      	<td style="padding-right:5em"><%= pic.id %></td>
      	<th style="padding-right:5em"><%= pic.tag %></th>
		<td><%= image_tag('/admin/serve/' + pic.id.to_s, :class => 'images_admin') %></td>
		<td><%= link_to 'Delete', picture_path(pic), method: :delete, data: {confirm: 'Are you sure?'}, :class=> 'destroy' %></td>
      </tr>
    <% end %>

  </tbody>
</table>
<br>
</div>
<br>
<hr>
<br>

game/app/views/dashboard/index.html.erb
<h1>Dashboard</h1>
<center>
	<a href="../play" id="start_game">Start Game</a>
</center>
<!--
<h4>Invite Players through mail</h4>
<input id="email" name="email" placeholder="Enter emails seperated by commas..." style="width:25%" />
-->

game/app/views/home/index.html.erb
<h1>Home</h1>

game/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Game</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<p>
<% if user_signed_in? %>
  <%= link_to 'Home', dashboard_index_path, :class => 'navbar-link' %> |
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>

<%= yield %>

</body>
</html>

game/app/views/pictures/new.html.erb
  <%= form_for :pictures, :html => {:multipart => true}, url: pictures_path do |f| %>
		<p> 
			<strong><%= f.label :tag %>:</strong><br>
			<%= f.text_field :tag %>
		</p>

		<p>
			<%= f.file_field :data%><br>
			<span>Max 65 KB formats(jpg)</span>
		</p>
		<p>
			<%= f.submit 'Add' %>
		</p>
	<% end %>

game/app/views/play/index.html.erb
<br>
<div id="result">
	<center>
		<h3 style="color: green;"><%= @attempts %> Attempts Remaining</h3>
	</center>
</div>
<center>
	<h4 id="score"></h4>
	<div id="next_btn" class="hidden" onclick="window.location='http://localhost:3000/play'">Next Question</div>
</center>
<div style="padding: 5px 10px 0px 10px;margin-left: 30%; margin-top: 3%;margin-right: 30%;background: white;box-shadow:0px 10px 20px 3px #d3d3d3;padding-bottom:20px;padding-top:20px;">
	<center>
		<% @count = 0 %>
		<% @selected.each do |i| %>
			<% @count = @count + 1 %>
			<%= image_tag('/admin/serve/' + i.id.to_s, :class => 'images_play') %>
			<% if @count == 2 %>
				<br>
			<%end%>
		<%end%>
	</center>
</div>

<div style="padding: 5px 10px 0px 10px;margin-left: 38%; margin-top: 3%;margin-right: 38%;background: white;box-shadow:0px 10px 20px 3px #d3d3d3;padding-bottom:20px;padding-top:20px;">
	<center>
		<input type="text" id="answer" name="answer" placeholder="Make your guess..." />
	</center>
</div>
<br><br>
<center>
	<div id="submit" onclick="check();">Submit</div>
</center>
<div id="quit" onclick="deleteCookie()"><center>Quit</center></div>


<script type="text/javascript">
	function getCookie(cname) {
   			 var name = cname + "=";
    		 var ca = document.cookie.split(';');
			    for(var i=0; i<ca.length; i++) {
			        var c = ca[i];
			        while (c.charAt(0)==' ') c = c.substring(1);
			        if (c.indexOf(name) != -1) return c.substring(name.length, c.length);
			    }
			    return "";
		}
	function deleteCookie () {
		document.cookie = "score=; expires=Thu, 01 Jan 1970 00:00:00 UTC";
		//window.location="";
	}
	var attempts = 3;
	var score = 0;
	if (getCookie("score") == "")
		document.cookie="score=" + score;
	else
		score = parseInt(getCookie("score"));
	function check () {
		var ans = document.getElementById('answer').value.toLowerCase().trim();
		if (ans == '<%= @tag.tag %>') {
			document.getElementById('result').innerHTML = "<center><h3 style='color: green'>Correct Answer!!</h3></center>";
			document.getElementById('next_btn').className = 'next';
			score += 3;
			document.cookie="score=" + score;
		}
		else {
			attempts = attempts - 1;
			if (attempts == 3){
				document.getElementById('result').innerHTML = "<center><h3 style='color: green;'><%= @attempts %> Attempts Remaining</h3></center>"
			};
			if (attempts == 2){
				document.getElementById('result').innerHTML = "<center><h3 style='color: orange;'>2 Attempts Remaining</h3></center>"
			};
			if (attempts == 1){
				document.getElementById('result').innerHTML = "<center><h3 style='color: red;'>1 Attempt Remaining</h3></center>"
			};
			console.log(attempts)
		};
	document.getElementById('score').innerHTML = "Score: " + getCookie("score");
	}
</script>